### ISSUE TITLE
Code Release Plan

### ISSUE THREAD

**Issue by yanqswhu** [sfchng/Gaussian-Activated-Radiance-Fields#2]
The results in your paper are very interesting and I can't wait to try them out.
Any plans to release code?

By the way, if I want to implement your code, the only thing I have to do is replace the pose encoding with a Gaussian activation function?

Thanks.

**Comment by yanqswhu** [comment]
One more question.

After reading through related papers, I found that setting a proper $\sigma$ is vital. 

Can you share your solutions to this? I didn't find out how to deal with this.

Thanks.

**Comment by astanziola** [comment]
@Yannnnnnnnnnnn Is it? I've been experimenting a little bit with gaussian activations on non-nerf applications yesterday, and I've found that I can use a relatively wide range of sigmas without much effects on the final results.
What changes, for me, is the behaviour of gradient descent at the beginning of the optimization
